language: ruby
services:
  - redis-server
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'create database www_rails_test;' -U postgres
script:
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - bundle exec rake spec
