
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: www-rails_development

test:
  <<: *default
  database: www-rails_test
  username: <%= ENV['TRAVIS'] == 'true' ? 'postgres' : '' %>
